/**
 * Image Registry — blog category
 * Auto-generated by scripts/split-images-registry.mjs
 * 10 entries
 */

import type { ImageMetadata } from './types';

export const IMAGES_BLOG: Record<string, ImageMetadata> = {
  "blog/airline-uniform-design-cultural-identity": {
    "slug": "airline-uniform-design-cultural-identity",
    "category": "blog",
    "subCategory": null,
    "industry": "aviation",
    "city": "jeddah",
    "path": "/images/blog/airline-uniform-design-cultural-identity.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/blog/airline-uniform-design-cultural-identity-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/blog/airline-uniform-design-cultural-identity-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/blog/airline-uniform-design-cultural-identity-1440.avif"
      }
    ],
    "webp": "/images/blog/airline-uniform-design-cultural-identity.webp",
    "description": "UNEOM editorial: airline uniform design cultural identity",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "aviation uniforms",
      "airline crew",
      "ground staff",
      "GACA compliant"
    ],
    "gps": {
      "lat": 21.4858,
      "lng": 39.1925
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:06:30 11:11:05",
    "creatorTool": "UNEOM Creative Department",
    "alt": "Editorial: airline uniform design cultural identity — UNEOM industry insights."
  },
  "blog/chef-uniform-design-guide": {
    "slug": "chef-uniform-design-guide",
    "category": "blog",
    "subCategory": null,
    "industry": "hospitality",
    "city": "jeddah",
    "path": "/images/blog/chef-uniform-design-guide.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/blog/chef-uniform-design-guide-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/blog/chef-uniform-design-guide-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/blog/chef-uniform-design-guide-1440.avif"
      }
    ],
    "webp": "/images/blog/chef-uniform-design-guide.webp",
    "description": "UNEOM editorial: chef uniform design guide",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "hospitality uniforms",
      "hotel staff",
      "F&B uniforms",
      "luxury service"
    ],
    "gps": {
      "lat": 21.4858,
      "lng": 39.1925
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:08:20 10:10:36",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "Editorial: chef uniform design guide — UNEOM industry insights."
  },
  "blog/circular-economy-uniforms": {
    "slug": "circular-economy-uniforms",
    "category": "blog",
    "subCategory": null,
    "industry": null,
    "city": "riyadh",
    "path": "/images/blog/circular-economy-uniforms.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/blog/circular-economy-uniforms-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/blog/circular-economy-uniforms-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/blog/circular-economy-uniforms-1440.avif"
      }
    ],
    "webp": "/images/blog/circular-economy-uniforms.webp",
    "description": "UNEOM editorial: circular economy uniforms",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:12:20 12:32:56",
    "creatorTool": "UNEOM Editorial Pipeline",
    "alt": "Editorial: circular economy uniforms — UNEOM industry insights."
  },
  "blog/corporate-uniform-psychology": {
    "slug": "corporate-uniform-psychology",
    "category": "blog",
    "subCategory": null,
    "industry": "corporate",
    "city": "riyadh",
    "path": "/images/blog/corporate-uniform-psychology.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/blog/corporate-uniform-psychology-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/blog/corporate-uniform-psychology-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/blog/corporate-uniform-psychology-1440.avif"
      }
    ],
    "webp": "/images/blog/corporate-uniform-psychology.webp",
    "description": "UNEOM editorial: corporate uniform psychology",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "corporate workwear",
      "business attire",
      "executive uniforms",
      "office wear"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:05:17 08:52:22",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "Editorial: corporate uniform psychology — UNEOM industry insights."
  },
  "blog/cultural-identity-saudi-school-uniforms": {
    "slug": "cultural-identity-saudi-school-uniforms",
    "category": "blog",
    "subCategory": null,
    "industry": "education",
    "city": "riyadh",
    "path": "/images/blog/cultural-identity-saudi-school-uniforms.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/blog/cultural-identity-saudi-school-uniforms-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/blog/cultural-identity-saudi-school-uniforms-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/blog/cultural-identity-saudi-school-uniforms-1440.avif"
      }
    ],
    "webp": "/images/blog/cultural-identity-saudi-school-uniforms.webp",
    "description": "UNEOM editorial: cultural identity saudi school uniforms",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "school uniforms",
      "student attire",
      "education sector",
      "MoE compliant"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:11:29 09:17:47",
    "creatorTool": "UNEOM Editorial Pipeline",
    "alt": "Editorial: cultural identity saudi school uniforms — UNEOM industry insights."
  },
  "blog/hajj-umrah-staff-uniforms": {
    "slug": "hajj-umrah-staff-uniforms",
    "category": "blog",
    "subCategory": null,
    "industry": null,
    "city": "riyadh",
    "path": "/images/blog/hajj-umrah-staff-uniforms.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/blog/hajj-umrah-staff-uniforms-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/blog/hajj-umrah-staff-uniforms-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/blog/hajj-umrah-staff-uniforms-1440.avif"
      }
    ],
    "webp": "/images/blog/hajj-umrah-staff-uniforms.webp",
    "description": "UNEOM editorial: hajj umrah staff uniforms",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:01:29 12:30:23",
    "creatorTool": "UNEOM Editorial Pipeline",
    "alt": "Editorial: hajj umrah staff uniforms — UNEOM industry insights."
  },
  "blog/hotel-staff-uniform-guide": {
    "slug": "hotel-staff-uniform-guide",
    "category": "blog",
    "subCategory": null,
    "industry": "hospitality",
    "city": "jeddah",
    "path": "/images/blog/hotel-staff-uniform-guide.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/blog/hotel-staff-uniform-guide-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/blog/hotel-staff-uniform-guide-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/blog/hotel-staff-uniform-guide-1440.avif"
      }
    ],
    "webp": "/images/blog/hotel-staff-uniform-guide.webp",
    "description": "UNEOM editorial: hotel staff uniform guide",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "hospitality uniforms",
      "hotel staff",
      "F&B uniforms",
      "luxury service"
    ],
    "gps": {
      "lat": 21.4858,
      "lng": 39.1925
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2026:04:12 18:39:49",
    "creatorTool": "UNEOM Editorial Pipeline",
    "alt": "Editorial: hotel staff uniform guide — UNEOM industry insights."
  },
  "blog/industrial-safety-workwear-saudi": {
    "slug": "industrial-safety-workwear-saudi",
    "category": "blog",
    "subCategory": null,
    "industry": "manufacturing",
    "city": "al-jubail",
    "path": "/images/blog/industrial-safety-workwear-saudi.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/blog/industrial-safety-workwear-saudi-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/blog/industrial-safety-workwear-saudi-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/blog/industrial-safety-workwear-saudi-1440.avif"
      }
    ],
    "webp": "/images/blog/industrial-safety-workwear-saudi.webp",
    "description": "UNEOM editorial: industrial safety workwear saudi",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "industrial uniforms",
      "FR coveralls",
      "PPE",
      "HCIS compliant",
      "workwear"
    ],
    "gps": {
      "lat": 27.0046,
      "lng": 49.661
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:02:27 11:53:54",
    "creatorTool": "UNEOM Design Lab",
    "alt": "Editorial: industrial safety workwear saudi — UNEOM industry insights."
  },
  "blog/medical-hijab-healthcare-standards": {
    "slug": "medical-hijab-healthcare-standards",
    "category": "blog",
    "subCategory": null,
    "industry": "healthcare",
    "city": "riyadh",
    "path": "/images/blog/medical-hijab-healthcare-standards.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/blog/medical-hijab-healthcare-standards-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/blog/medical-hijab-healthcare-standards-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/blog/medical-hijab-healthcare-standards-1440.avif"
      }
    ],
    "webp": "/images/blog/medical-hijab-healthcare-standards.webp",
    "description": "UNEOM editorial: medical hijab healthcare standards",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "medical scrubs",
      "healthcare uniforms",
      "hospital attire",
      "MoH compliant"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:02:06 17:54:27",
    "creatorTool": "UNEOM Design Lab",
    "alt": "Editorial: medical hijab healthcare standards — UNEOM industry insights."
  },
  "blog/medical-scrubs-evolution-saudi": {
    "slug": "medical-scrubs-evolution-saudi",
    "category": "blog",
    "subCategory": null,
    "industry": "healthcare",
    "city": "riyadh",
    "path": "/images/blog/medical-scrubs-evolution-saudi.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/blog/medical-scrubs-evolution-saudi-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/blog/medical-scrubs-evolution-saudi-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/blog/medical-scrubs-evolution-saudi-1440.avif"
      }
    ],
    "webp": "/images/blog/medical-scrubs-evolution-saudi.webp",
    "description": "UNEOM editorial: medical scrubs evolution saudi",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "medical scrubs",
      "healthcare uniforms",
      "hospital attire",
      "MoH compliant"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:08:09 18:57:19",
    "creatorTool": "UNEOM Design Lab",
    "alt": "Editorial: medical scrubs evolution saudi — UNEOM industry insights."
  }
};
