/**
 * Image Registry — case-studies category
 * Auto-generated by scripts/split-images-registry.mjs
 * 16 entries
 */

import type { ImageMetadata } from './types';

export const IMAGES_CASE_STUDIES: Record<string, ImageMetadata> = {
  "case-studies/5-star-hotel-spa/after": {
    "slug": "after",
    "category": "case-studies",
    "subCategory": "5-star-hotel-spa",
    "industry": null,
    "city": "riyadh",
    "path": "/images/case-studies/5-star-hotel-spa/after.avif",
    "width": 1200,
    "height": 900,
    "variants": [
      {
        "width": 600,
        "height": 450,
        "path": "/images/case-studies/5-star-hotel-spa/after-600.avif"
      },
      {
        "width": 900,
        "height": 675,
        "path": "/images/case-studies/5-star-hotel-spa/after-900.avif"
      }
    ],
    "webp": "/images/case-studies/5-star-hotel-spa/after.webp",
    "description": "UNEOM case study — 5 star hotel spa transformation",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:09:25 16:38:12",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "5 star hotel spa — after UNEOM transformation."
  },
  "case-studies/5-star-hotel-spa/before": {
    "slug": "before",
    "category": "case-studies",
    "subCategory": "5-star-hotel-spa",
    "industry": null,
    "city": "riyadh",
    "path": "/images/case-studies/5-star-hotel-spa/before.avif",
    "width": 1200,
    "height": 900,
    "variants": [
      {
        "width": 600,
        "height": 450,
        "path": "/images/case-studies/5-star-hotel-spa/before-600.avif"
      },
      {
        "width": 900,
        "height": 675,
        "path": "/images/case-studies/5-star-hotel-spa/before-900.avif"
      }
    ],
    "webp": "/images/case-studies/5-star-hotel-spa/before.webp",
    "description": "UNEOM case study — 5 star hotel spa transformation",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2026:03:18 18:44:07",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "5 star hotel spa — before UNEOM engagement."
  },
  "case-studies/beauty-chain-standardization/after": {
    "slug": "after",
    "category": "case-studies",
    "subCategory": "beauty-chain-standardization",
    "industry": null,
    "city": "riyadh",
    "path": "/images/case-studies/beauty-chain-standardization/after.avif",
    "width": 1200,
    "height": 900,
    "variants": [
      {
        "width": 600,
        "height": 450,
        "path": "/images/case-studies/beauty-chain-standardization/after-600.avif"
      },
      {
        "width": 900,
        "height": 675,
        "path": "/images/case-studies/beauty-chain-standardization/after-900.avif"
      }
    ],
    "webp": "/images/case-studies/beauty-chain-standardization/after.webp",
    "description": "UNEOM case study — beauty chain standardization transformation",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:09:25 16:38:12",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "beauty chain standardization — after UNEOM transformation."
  },
  "case-studies/beauty-chain-standardization/before": {
    "slug": "before",
    "category": "case-studies",
    "subCategory": "beauty-chain-standardization",
    "industry": null,
    "city": "riyadh",
    "path": "/images/case-studies/beauty-chain-standardization/before.avif",
    "width": 1200,
    "height": 900,
    "variants": [
      {
        "width": 600,
        "height": 450,
        "path": "/images/case-studies/beauty-chain-standardization/before-600.avif"
      },
      {
        "width": 900,
        "height": 675,
        "path": "/images/case-studies/beauty-chain-standardization/before-900.avif"
      }
    ],
    "webp": "/images/case-studies/beauty-chain-standardization/before.webp",
    "description": "UNEOM case study — beauty chain standardization transformation",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2026:03:18 18:44:07",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "beauty chain standardization — before UNEOM engagement."
  },
  "case-studies/factory-safety-improvement/after": {
    "slug": "after",
    "category": "case-studies",
    "subCategory": "factory-safety-improvement",
    "industry": null,
    "city": "riyadh",
    "path": "/images/case-studies/factory-safety-improvement/after.avif",
    "width": 1200,
    "height": 900,
    "variants": [
      {
        "width": 600,
        "height": 450,
        "path": "/images/case-studies/factory-safety-improvement/after-600.avif"
      },
      {
        "width": 900,
        "height": 675,
        "path": "/images/case-studies/factory-safety-improvement/after-900.avif"
      }
    ],
    "webp": "/images/case-studies/factory-safety-improvement/after.webp",
    "description": "UNEOM case study — factory safety improvement transformation",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:09:25 16:38:12",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "factory safety improvement — after UNEOM transformation."
  },
  "case-studies/factory-safety-improvement/before": {
    "slug": "before",
    "category": "case-studies",
    "subCategory": "factory-safety-improvement",
    "industry": null,
    "city": "riyadh",
    "path": "/images/case-studies/factory-safety-improvement/before.avif",
    "width": 1200,
    "height": 900,
    "variants": [
      {
        "width": 600,
        "height": 450,
        "path": "/images/case-studies/factory-safety-improvement/before-600.avif"
      },
      {
        "width": 900,
        "height": 675,
        "path": "/images/case-studies/factory-safety-improvement/before-900.avif"
      }
    ],
    "webp": "/images/case-studies/factory-safety-improvement/before.webp",
    "description": "UNEOM case study — factory safety improvement transformation",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2026:03:18 18:44:07",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "factory safety improvement — before UNEOM engagement."
  },
  "case-studies/hospital-aesthetic/after": {
    "slug": "after",
    "category": "case-studies",
    "subCategory": "hospital-aesthetic",
    "industry": null,
    "city": "riyadh",
    "path": "/images/case-studies/hospital-aesthetic/after.avif",
    "width": 1200,
    "height": 900,
    "variants": [
      {
        "width": 600,
        "height": 450,
        "path": "/images/case-studies/hospital-aesthetic/after-600.avif"
      },
      {
        "width": 900,
        "height": 675,
        "path": "/images/case-studies/hospital-aesthetic/after-900.avif"
      }
    ],
    "webp": "/images/case-studies/hospital-aesthetic/after.webp",
    "description": "UNEOM case study — hospital aesthetic transformation",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:09:25 16:38:12",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "hospital aesthetic — after UNEOM transformation."
  },
  "case-studies/hospital-aesthetic/before": {
    "slug": "before",
    "category": "case-studies",
    "subCategory": "hospital-aesthetic",
    "industry": null,
    "city": "riyadh",
    "path": "/images/case-studies/hospital-aesthetic/before.avif",
    "width": 1200,
    "height": 900,
    "variants": [
      {
        "width": 600,
        "height": 450,
        "path": "/images/case-studies/hospital-aesthetic/before-600.avif"
      },
      {
        "width": 900,
        "height": 675,
        "path": "/images/case-studies/hospital-aesthetic/before-900.avif"
      }
    ],
    "webp": "/images/case-studies/hospital-aesthetic/before.webp",
    "description": "UNEOM case study — hospital aesthetic transformation",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2026:03:18 18:44:07",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "hospital aesthetic — before UNEOM engagement."
  },
  "case-studies/luxury-salon/after": {
    "slug": "after",
    "category": "case-studies",
    "subCategory": "luxury-salon",
    "industry": null,
    "city": "riyadh",
    "path": "/images/case-studies/luxury-salon/after.avif",
    "width": 1200,
    "height": 900,
    "variants": [
      {
        "width": 600,
        "height": 450,
        "path": "/images/case-studies/luxury-salon/after-600.avif"
      },
      {
        "width": 900,
        "height": 675,
        "path": "/images/case-studies/luxury-salon/after-900.avif"
      }
    ],
    "webp": "/images/case-studies/luxury-salon/after.webp",
    "description": "UNEOM case study — luxury salon transformation",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:09:25 16:38:12",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "luxury salon — after UNEOM transformation."
  },
  "case-studies/luxury-salon/before": {
    "slug": "before",
    "category": "case-studies",
    "subCategory": "luxury-salon",
    "industry": null,
    "city": "riyadh",
    "path": "/images/case-studies/luxury-salon/before.avif",
    "width": 1200,
    "height": 900,
    "variants": [
      {
        "width": 600,
        "height": 450,
        "path": "/images/case-studies/luxury-salon/before-600.avif"
      },
      {
        "width": 900,
        "height": 675,
        "path": "/images/case-studies/luxury-salon/before-900.avif"
      }
    ],
    "webp": "/images/case-studies/luxury-salon/before.webp",
    "description": "UNEOM case study — luxury salon transformation",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2026:03:18 18:44:07",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "luxury salon — before UNEOM engagement."
  },
  "case-studies/nationwide-retail-branding/after": {
    "slug": "after",
    "category": "case-studies",
    "subCategory": "nationwide-retail-branding",
    "industry": null,
    "city": "riyadh",
    "path": "/images/case-studies/nationwide-retail-branding/after.avif",
    "width": 1200,
    "height": 900,
    "variants": [
      {
        "width": 600,
        "height": 450,
        "path": "/images/case-studies/nationwide-retail-branding/after-600.avif"
      },
      {
        "width": 900,
        "height": 675,
        "path": "/images/case-studies/nationwide-retail-branding/after-900.avif"
      }
    ],
    "webp": "/images/case-studies/nationwide-retail-branding/after.webp",
    "description": "UNEOM case study — nationwide retail branding transformation",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:09:25 16:38:12",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "nationwide retail branding — after UNEOM transformation."
  },
  "case-studies/nationwide-retail-branding/before": {
    "slug": "before",
    "category": "case-studies",
    "subCategory": "nationwide-retail-branding",
    "industry": null,
    "city": "riyadh",
    "path": "/images/case-studies/nationwide-retail-branding/before.avif",
    "width": 1200,
    "height": 900,
    "variants": [
      {
        "width": 600,
        "height": 450,
        "path": "/images/case-studies/nationwide-retail-branding/before-600.avif"
      },
      {
        "width": 900,
        "height": 675,
        "path": "/images/case-studies/nationwide-retail-branding/before-900.avif"
      }
    ],
    "webp": "/images/case-studies/nationwide-retail-branding/before.webp",
    "description": "UNEOM case study — nationwide retail branding transformation",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2026:03:18 18:44:07",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "nationwide retail branding — before UNEOM engagement."
  },
  "case-studies/retail-brand-transformation/after": {
    "slug": "after",
    "category": "case-studies",
    "subCategory": "retail-brand-transformation",
    "industry": null,
    "city": "riyadh",
    "path": "/images/case-studies/retail-brand-transformation/after.avif",
    "width": 1200,
    "height": 900,
    "variants": [
      {
        "width": 600,
        "height": 450,
        "path": "/images/case-studies/retail-brand-transformation/after-600.avif"
      },
      {
        "width": 900,
        "height": 675,
        "path": "/images/case-studies/retail-brand-transformation/after-900.avif"
      }
    ],
    "webp": "/images/case-studies/retail-brand-transformation/after.webp",
    "description": "UNEOM case study — retail brand transformation transformation",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:09:25 16:38:12",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "retail brand transformation — after UNEOM transformation."
  },
  "case-studies/retail-brand-transformation/before": {
    "slug": "before",
    "category": "case-studies",
    "subCategory": "retail-brand-transformation",
    "industry": null,
    "city": "riyadh",
    "path": "/images/case-studies/retail-brand-transformation/before.avif",
    "width": 1200,
    "height": 900,
    "variants": [
      {
        "width": 600,
        "height": 450,
        "path": "/images/case-studies/retail-brand-transformation/before-600.avif"
      },
      {
        "width": 900,
        "height": 675,
        "path": "/images/case-studies/retail-brand-transformation/before-900.avif"
      }
    ],
    "webp": "/images/case-studies/retail-brand-transformation/before.webp",
    "description": "UNEOM case study — retail brand transformation transformation",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2026:03:18 18:44:07",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "retail brand transformation — before UNEOM engagement."
  },
  "case-studies/spa-chain-rebranding/after": {
    "slug": "after",
    "category": "case-studies",
    "subCategory": "spa-chain-rebranding",
    "industry": null,
    "city": "riyadh",
    "path": "/images/case-studies/spa-chain-rebranding/after.avif",
    "width": 1200,
    "height": 900,
    "variants": [
      {
        "width": 600,
        "height": 450,
        "path": "/images/case-studies/spa-chain-rebranding/after-600.avif"
      },
      {
        "width": 900,
        "height": 675,
        "path": "/images/case-studies/spa-chain-rebranding/after-900.avif"
      }
    ],
    "webp": "/images/case-studies/spa-chain-rebranding/after.webp",
    "description": "UNEOM case study — spa chain rebranding transformation",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:09:25 16:38:12",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "spa chain rebranding — after UNEOM transformation."
  },
  "case-studies/spa-chain-rebranding/before": {
    "slug": "before",
    "category": "case-studies",
    "subCategory": "spa-chain-rebranding",
    "industry": null,
    "city": "riyadh",
    "path": "/images/case-studies/spa-chain-rebranding/before.avif",
    "width": 1200,
    "height": 900,
    "variants": [
      {
        "width": 600,
        "height": 450,
        "path": "/images/case-studies/spa-chain-rebranding/before-600.avif"
      },
      {
        "width": 900,
        "height": 675,
        "path": "/images/case-studies/spa-chain-rebranding/before-900.avif"
      }
    ],
    "webp": "/images/case-studies/spa-chain-rebranding/before.webp",
    "description": "UNEOM case study — spa chain rebranding transformation",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2026:03:18 18:44:07",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "spa chain rebranding — before UNEOM engagement."
  }
};
