/**
 * Image Registry — cities category
 * Auto-generated by scripts/split-images-registry.mjs
 * 24 entries
 */

import type { ImageMetadata } from './types';

export const IMAGES_CITIES: Record<string, ImageMetadata> = {
  "cities/hero-abha": {
    "slug": "hero-abha",
    "category": "cities",
    "subCategory": null,
    "industry": null,
    "city": "abha",
    "path": "/images/cities/hero-abha.avif",
    "width": 1920,
    "height": 800,
    "variants": [
      {
        "width": 640,
        "height": 267,
        "path": "/images/cities/hero-abha-640.avif"
      },
      {
        "width": 960,
        "height": 400,
        "path": "/images/cities/hero-abha-960.avif"
      },
      {
        "width": 1440,
        "height": 600,
        "path": "/images/cities/hero-abha-1440.avif"
      }
    ],
    "webp": "/images/cities/hero-abha.webp",
    "description": "UNEOM professional uniforms in Abha, Asir Province, Saudi Arabia",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "Abha",
      "Asir Province"
    ],
    "gps": {
      "lat": 18.2164,
      "lng": 42.5053
    },
    "location": {
      "sublocation": "Al-Sad",
      "city": "Abha",
      "state": "Asir Province",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:10:19 14:12:45",
    "creatorTool": "UNEOM Editorial Pipeline",
    "alt": "UNEOM professional uniforms serving Abha in Asir Province, Saudi Arabia."
  },
  "cities/hero-al-ahsa": {
    "slug": "hero-al-ahsa",
    "category": "cities",
    "subCategory": null,
    "industry": null,
    "city": "al-ahsa",
    "path": "/images/cities/hero-al-ahsa.avif",
    "width": 1920,
    "height": 800,
    "variants": [
      {
        "width": 640,
        "height": 267,
        "path": "/images/cities/hero-al-ahsa-640.avif"
      },
      {
        "width": 960,
        "height": 400,
        "path": "/images/cities/hero-al-ahsa-960.avif"
      },
      {
        "width": 1440,
        "height": 600,
        "path": "/images/cities/hero-al-ahsa-1440.avif"
      }
    ],
    "webp": "/images/cities/hero-al-ahsa.webp",
    "description": "UNEOM professional uniforms in Al-Ahsa, Eastern Province, Saudi Arabia",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "Al-Ahsa",
      "Eastern Province"
    ],
    "gps": {
      "lat": 25.4295,
      "lng": 49.5917
    },
    "location": {
      "sublocation": "Oasis",
      "city": "Al-Ahsa",
      "state": "Eastern Province",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:04:23 16:56:20",
    "creatorTool": "UNEOM Editorial Pipeline",
    "alt": "UNEOM professional uniforms serving Al-Ahsa in Eastern Province, Saudi Arabia."
  },
  "cities/hero-al-baha": {
    "slug": "hero-al-baha",
    "category": "cities",
    "subCategory": null,
    "industry": null,
    "city": "al-baha",
    "path": "/images/cities/hero-al-baha.avif",
    "width": 1920,
    "height": 800,
    "variants": [
      {
        "width": 640,
        "height": 267,
        "path": "/images/cities/hero-al-baha-640.avif"
      },
      {
        "width": 960,
        "height": 400,
        "path": "/images/cities/hero-al-baha-960.avif"
      },
      {
        "width": 1440,
        "height": 600,
        "path": "/images/cities/hero-al-baha-1440.avif"
      }
    ],
    "webp": "/images/cities/hero-al-baha.webp",
    "description": "UNEOM professional uniforms in Al-Baha, Al-Baha Province, Saudi Arabia",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "Al-Baha",
      "Al-Baha Province"
    ],
    "gps": {
      "lat": 20.0129,
      "lng": 41.4677
    },
    "location": {
      "sublocation": "Al-Aqiq",
      "city": "Al-Baha",
      "state": "Al-Baha Province",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:10:17 18:11:08",
    "creatorTool": "UNEOM Design Lab",
    "alt": "UNEOM professional uniforms serving Al-Baha in Al-Baha Province, Saudi Arabia."
  },
  "cities/hero-al-jubail": {
    "slug": "hero-al-jubail",
    "category": "cities",
    "subCategory": null,
    "industry": null,
    "city": "al-jubail",
    "path": "/images/cities/hero-al-jubail.avif",
    "width": 1920,
    "height": 800,
    "variants": [
      {
        "width": 640,
        "height": 267,
        "path": "/images/cities/hero-al-jubail-640.avif"
      },
      {
        "width": 960,
        "height": 400,
        "path": "/images/cities/hero-al-jubail-960.avif"
      },
      {
        "width": 1440,
        "height": 600,
        "path": "/images/cities/hero-al-jubail-1440.avif"
      }
    ],
    "webp": "/images/cities/hero-al-jubail.webp",
    "description": "UNEOM professional uniforms in Al-Jubail, Eastern Province, Saudi Arabia",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "Al-Jubail",
      "Eastern Province"
    ],
    "gps": {
      "lat": 27.0046,
      "lng": 49.661
    },
    "location": {
      "sublocation": "Al-Fanateer",
      "city": "Al-Jubail",
      "state": "Eastern Province",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:06:28 11:11:15",
    "creatorTool": "UNEOM Production House",
    "alt": "UNEOM professional uniforms serving Al-Jubail in Eastern Province, Saudi Arabia."
  },
  "cities/hero-al-kharj": {
    "slug": "hero-al-kharj",
    "category": "cities",
    "subCategory": null,
    "industry": null,
    "city": "al-kharj",
    "path": "/images/cities/hero-al-kharj.avif",
    "width": 1920,
    "height": 800,
    "variants": [
      {
        "width": 640,
        "height": 267,
        "path": "/images/cities/hero-al-kharj-640.avif"
      },
      {
        "width": 960,
        "height": 400,
        "path": "/images/cities/hero-al-kharj-960.avif"
      },
      {
        "width": 1440,
        "height": 600,
        "path": "/images/cities/hero-al-kharj-1440.avif"
      }
    ],
    "webp": "/images/cities/hero-al-kharj.webp",
    "description": "UNEOM professional uniforms in Al-Kharj, Riyadh Province, Saudi Arabia",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "Al-Kharj",
      "Riyadh Province"
    ],
    "gps": {
      "lat": 24.1554,
      "lng": 47.3346
    },
    "location": {
      "sublocation": "Al-Yamamah",
      "city": "Al-Kharj",
      "state": "Riyadh Province",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:08:04 08:40:29",
    "creatorTool": "UNEOM Editorial Pipeline",
    "alt": "UNEOM professional uniforms serving Al-Kharj in Riyadh Province, Saudi Arabia."
  },
  "cities/hero-al-qatif": {
    "slug": "hero-al-qatif",
    "category": "cities",
    "subCategory": null,
    "industry": null,
    "city": "al-qatif",
    "path": "/images/cities/hero-al-qatif.avif",
    "width": 1920,
    "height": 800,
    "variants": [
      {
        "width": 640,
        "height": 267,
        "path": "/images/cities/hero-al-qatif-640.avif"
      },
      {
        "width": 960,
        "height": 400,
        "path": "/images/cities/hero-al-qatif-960.avif"
      },
      {
        "width": 1440,
        "height": 600,
        "path": "/images/cities/hero-al-qatif-1440.avif"
      }
    ],
    "webp": "/images/cities/hero-al-qatif.webp",
    "description": "UNEOM professional uniforms in Al-Qatif, Eastern Province, Saudi Arabia",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "Al-Qatif",
      "Eastern Province"
    ],
    "gps": {
      "lat": 26.5573,
      "lng": 49.9962
    },
    "location": {
      "sublocation": "Old Souq",
      "city": "Al-Qatif",
      "state": "Eastern Province",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:01:15 14:25:05",
    "creatorTool": "UNEOM Design Lab",
    "alt": "UNEOM professional uniforms serving Al-Qatif in Eastern Province, Saudi Arabia."
  },
  "cities/hero-arar": {
    "slug": "hero-arar",
    "category": "cities",
    "subCategory": null,
    "industry": null,
    "city": "arar",
    "path": "/images/cities/hero-arar.avif",
    "width": 1920,
    "height": 800,
    "variants": [
      {
        "width": 640,
        "height": 267,
        "path": "/images/cities/hero-arar-640.avif"
      },
      {
        "width": 960,
        "height": 400,
        "path": "/images/cities/hero-arar-960.avif"
      },
      {
        "width": 1440,
        "height": 600,
        "path": "/images/cities/hero-arar-1440.avif"
      }
    ],
    "webp": "/images/cities/hero-arar.webp",
    "description": "UNEOM professional uniforms in Arar, Northern Borders Province, Saudi Arabia",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "Arar",
      "Northern Borders Province"
    ],
    "gps": {
      "lat": 30.9753,
      "lng": 41.0381
    },
    "location": {
      "sublocation": "Al-Salam",
      "city": "Arar",
      "state": "Northern Borders Province",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:08:05 16:36:03",
    "creatorTool": "UNEOM Creative Department",
    "alt": "UNEOM professional uniforms serving Arar in Northern Borders Province, Saudi Arabia."
  },
  "cities/hero-buraidah": {
    "slug": "hero-buraidah",
    "category": "cities",
    "subCategory": null,
    "industry": null,
    "city": "buraidah",
    "path": "/images/cities/hero-buraidah.avif",
    "width": 1920,
    "height": 800,
    "variants": [
      {
        "width": 640,
        "height": 267,
        "path": "/images/cities/hero-buraidah-640.avif"
      },
      {
        "width": 960,
        "height": 400,
        "path": "/images/cities/hero-buraidah-960.avif"
      },
      {
        "width": 1440,
        "height": 600,
        "path": "/images/cities/hero-buraidah-1440.avif"
      }
    ],
    "webp": "/images/cities/hero-buraidah.webp",
    "description": "UNEOM professional uniforms in Buraidah, Qassim Province, Saudi Arabia",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "Buraidah",
      "Qassim Province"
    ],
    "gps": {
      "lat": 26.326,
      "lng": 43.975
    },
    "location": {
      "sublocation": "Al-Rabwa",
      "city": "Buraidah",
      "state": "Qassim Province",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:03:27 14:09:40",
    "creatorTool": "UNEOM Creative Department",
    "alt": "UNEOM professional uniforms serving Buraidah in Qassim Province, Saudi Arabia."
  },
  "cities/hero-dammam": {
    "slug": "hero-dammam",
    "category": "cities",
    "subCategory": null,
    "industry": null,
    "city": "dammam",
    "path": "/images/cities/hero-dammam.avif",
    "width": 1920,
    "height": 800,
    "variants": [
      {
        "width": 640,
        "height": 267,
        "path": "/images/cities/hero-dammam-640.avif"
      },
      {
        "width": 960,
        "height": 400,
        "path": "/images/cities/hero-dammam-960.avif"
      },
      {
        "width": 1440,
        "height": 600,
        "path": "/images/cities/hero-dammam-1440.avif"
      }
    ],
    "webp": "/images/cities/hero-dammam.webp",
    "description": "UNEOM professional uniforms in Dammam, Eastern Province, Saudi Arabia",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "Dammam",
      "Eastern Province"
    ],
    "gps": {
      "lat": 26.4207,
      "lng": 50.0888
    },
    "location": {
      "sublocation": "Al-Rabi",
      "city": "Dammam",
      "state": "Eastern Province",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:11:18 16:52:02",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "UNEOM professional uniforms serving Dammam in Eastern Province, Saudi Arabia."
  },
  "cities/hero-dhahran": {
    "slug": "hero-dhahran",
    "category": "cities",
    "subCategory": null,
    "industry": null,
    "city": "dhahran",
    "path": "/images/cities/hero-dhahran.avif",
    "width": 1920,
    "height": 800,
    "variants": [
      {
        "width": 640,
        "height": 267,
        "path": "/images/cities/hero-dhahran-640.avif"
      },
      {
        "width": 960,
        "height": 400,
        "path": "/images/cities/hero-dhahran-960.avif"
      },
      {
        "width": 1440,
        "height": 600,
        "path": "/images/cities/hero-dhahran-1440.avif"
      }
    ],
    "webp": "/images/cities/hero-dhahran.webp",
    "description": "UNEOM professional uniforms in Dhahran, Eastern Province, Saudi Arabia",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "Dhahran",
      "Eastern Province"
    ],
    "gps": {
      "lat": 26.2361,
      "lng": 50.0393
    },
    "location": {
      "sublocation": "Al-Doha",
      "city": "Dhahran",
      "state": "Eastern Province",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:11:07 10:12:45",
    "creatorTool": "UNEOM Creative Department",
    "alt": "UNEOM professional uniforms serving Dhahran in Eastern Province, Saudi Arabia."
  },
  "cities/hero-hail": {
    "slug": "hero-hail",
    "category": "cities",
    "subCategory": null,
    "industry": null,
    "city": "hail",
    "path": "/images/cities/hero-hail.avif",
    "width": 1920,
    "height": 800,
    "variants": [
      {
        "width": 640,
        "height": 267,
        "path": "/images/cities/hero-hail-640.avif"
      },
      {
        "width": 960,
        "height": 400,
        "path": "/images/cities/hero-hail-960.avif"
      },
      {
        "width": 1440,
        "height": 600,
        "path": "/images/cities/hero-hail-1440.avif"
      }
    ],
    "webp": "/images/cities/hero-hail.webp",
    "description": "UNEOM professional uniforms in Hail, Hail Province, Saudi Arabia",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "Hail",
      "Hail Province"
    ],
    "gps": {
      "lat": 27.5114,
      "lng": 41.69
    },
    "location": {
      "sublocation": "Al-Khuzama",
      "city": "Hail",
      "state": "Hail Province",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:08:14 13:30:28",
    "creatorTool": "UNEOM Production House",
    "alt": "UNEOM professional uniforms serving Hail in Hail Province, Saudi Arabia."
  },
  "cities/hero-jazan": {
    "slug": "hero-jazan",
    "category": "cities",
    "subCategory": null,
    "industry": null,
    "city": "jazan",
    "path": "/images/cities/hero-jazan.avif",
    "width": 1920,
    "height": 800,
    "variants": [
      {
        "width": 640,
        "height": 267,
        "path": "/images/cities/hero-jazan-640.avif"
      },
      {
        "width": 960,
        "height": 400,
        "path": "/images/cities/hero-jazan-960.avif"
      },
      {
        "width": 1440,
        "height": 600,
        "path": "/images/cities/hero-jazan-1440.avif"
      }
    ],
    "webp": "/images/cities/hero-jazan.webp",
    "description": "UNEOM professional uniforms in Jazan, Jazan Province, Saudi Arabia",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "Jazan",
      "Jazan Province"
    ],
    "gps": {
      "lat": 16.8892,
      "lng": 42.5511
    },
    "location": {
      "sublocation": "Corniche",
      "city": "Jazan",
      "state": "Jazan Province",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:01:20 11:19:44",
    "creatorTool": "UNEOM Creative Department",
    "alt": "UNEOM professional uniforms serving Jazan in Jazan Province, Saudi Arabia."
  },
  "cities/hero-jeddah": {
    "slug": "hero-jeddah",
    "category": "cities",
    "subCategory": null,
    "industry": null,
    "city": "jeddah",
    "path": "/images/cities/hero-jeddah.avif",
    "width": 1920,
    "height": 800,
    "variants": [
      {
        "width": 640,
        "height": 267,
        "path": "/images/cities/hero-jeddah-640.avif"
      },
      {
        "width": 960,
        "height": 400,
        "path": "/images/cities/hero-jeddah-960.avif"
      },
      {
        "width": 1440,
        "height": 600,
        "path": "/images/cities/hero-jeddah-1440.avif"
      }
    ],
    "webp": "/images/cities/hero-jeddah.webp",
    "description": "UNEOM professional uniforms in Jeddah, Makkah Province, Saudi Arabia",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "Jeddah",
      "Makkah Province"
    ],
    "gps": {
      "lat": 21.4858,
      "lng": 39.1925
    },
    "location": {
      "sublocation": "Al-Hamra",
      "city": "Jeddah",
      "state": "Makkah Province",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:03:12 17:46:18",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "UNEOM professional uniforms serving Jeddah in Makkah Province, Saudi Arabia."
  },
  "cities/hero-khamis-mushait": {
    "slug": "hero-khamis-mushait",
    "category": "cities",
    "subCategory": null,
    "industry": null,
    "city": "khamis-mushait",
    "path": "/images/cities/hero-khamis-mushait.avif",
    "width": 1920,
    "height": 800,
    "variants": [
      {
        "width": 640,
        "height": 267,
        "path": "/images/cities/hero-khamis-mushait-640.avif"
      },
      {
        "width": 960,
        "height": 400,
        "path": "/images/cities/hero-khamis-mushait-960.avif"
      },
      {
        "width": 1440,
        "height": 600,
        "path": "/images/cities/hero-khamis-mushait-1440.avif"
      }
    ],
    "webp": "/images/cities/hero-khamis-mushait.webp",
    "description": "UNEOM professional uniforms in Khamis Mushait, Asir Province, Saudi Arabia",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "Khamis Mushait",
      "Asir Province"
    ],
    "gps": {
      "lat": 18.306,
      "lng": 42.7298
    },
    "location": {
      "sublocation": "Al-Tabab",
      "city": "Khamis Mushait",
      "state": "Asir Province",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:10:01 18:16:11",
    "creatorTool": "UNEOM Design Lab",
    "alt": "UNEOM professional uniforms serving Khamis Mushait in Asir Province, Saudi Arabia."
  },
  "cities/hero-khobar": {
    "slug": "hero-khobar",
    "category": "cities",
    "subCategory": null,
    "industry": null,
    "city": "khobar",
    "path": "/images/cities/hero-khobar.avif",
    "width": 1920,
    "height": 800,
    "variants": [
      {
        "width": 640,
        "height": 267,
        "path": "/images/cities/hero-khobar-640.avif"
      },
      {
        "width": 960,
        "height": 400,
        "path": "/images/cities/hero-khobar-960.avif"
      },
      {
        "width": 1440,
        "height": 600,
        "path": "/images/cities/hero-khobar-1440.avif"
      }
    ],
    "webp": "/images/cities/hero-khobar.webp",
    "description": "UNEOM professional uniforms in Khobar, Eastern Province, Saudi Arabia",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "Khobar",
      "Eastern Province"
    ],
    "gps": {
      "lat": 26.2172,
      "lng": 50.1971
    },
    "location": {
      "sublocation": "Al-Bandariyah",
      "city": "Khobar",
      "state": "Eastern Province",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:08:29 12:22:16",
    "creatorTool": "UNEOM Design Lab",
    "alt": "UNEOM professional uniforms serving Khobar in Eastern Province, Saudi Arabia."
  },
  "cities/hero-mecca": {
    "slug": "hero-mecca",
    "category": "cities",
    "subCategory": null,
    "industry": null,
    "city": "mecca",
    "path": "/images/cities/hero-mecca.avif",
    "width": 1920,
    "height": 800,
    "variants": [
      {
        "width": 640,
        "height": 267,
        "path": "/images/cities/hero-mecca-640.avif"
      },
      {
        "width": 960,
        "height": 400,
        "path": "/images/cities/hero-mecca-960.avif"
      },
      {
        "width": 1440,
        "height": 600,
        "path": "/images/cities/hero-mecca-1440.avif"
      }
    ],
    "webp": "/images/cities/hero-mecca.webp",
    "description": "UNEOM professional uniforms in Mecca, Makkah Province, Saudi Arabia",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "Mecca",
      "Makkah Province"
    ],
    "gps": {
      "lat": 21.4225,
      "lng": 39.8262
    },
    "location": {
      "sublocation": "Al-Naseem",
      "city": "Mecca",
      "state": "Makkah Province",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:12:30 17:55:24",
    "creatorTool": "UNEOM Editorial Pipeline",
    "alt": "UNEOM professional uniforms serving Mecca in Makkah Province, Saudi Arabia."
  },
  "cities/hero-medina": {
    "slug": "hero-medina",
    "category": "cities",
    "subCategory": null,
    "industry": null,
    "city": "medina",
    "path": "/images/cities/hero-medina.avif",
    "width": 1920,
    "height": 800,
    "variants": [
      {
        "width": 640,
        "height": 267,
        "path": "/images/cities/hero-medina-640.avif"
      },
      {
        "width": 960,
        "height": 400,
        "path": "/images/cities/hero-medina-960.avif"
      },
      {
        "width": 1440,
        "height": 600,
        "path": "/images/cities/hero-medina-1440.avif"
      }
    ],
    "webp": "/images/cities/hero-medina.webp",
    "description": "UNEOM professional uniforms in Medina, Madinah Province, Saudi Arabia",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "Medina",
      "Madinah Province"
    ],
    "gps": {
      "lat": 24.4682,
      "lng": 39.6111
    },
    "location": {
      "sublocation": "Al-Anbariya",
      "city": "Medina",
      "state": "Madinah Province",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:07:04 14:46:26",
    "creatorTool": "UNEOM Editorial Pipeline",
    "alt": "UNEOM professional uniforms serving Medina in Madinah Province, Saudi Arabia."
  },
  "cities/hero-najran": {
    "slug": "hero-najran",
    "category": "cities",
    "subCategory": null,
    "industry": null,
    "city": "najran",
    "path": "/images/cities/hero-najran.avif",
    "width": 1920,
    "height": 800,
    "variants": [
      {
        "width": 640,
        "height": 267,
        "path": "/images/cities/hero-najran-640.avif"
      },
      {
        "width": 960,
        "height": 400,
        "path": "/images/cities/hero-najran-960.avif"
      },
      {
        "width": 1440,
        "height": 600,
        "path": "/images/cities/hero-najran-1440.avif"
      }
    ],
    "webp": "/images/cities/hero-najran.webp",
    "description": "UNEOM professional uniforms in Najran, Najran Province, Saudi Arabia",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "Najran",
      "Najran Province"
    ],
    "gps": {
      "lat": 17.4924,
      "lng": 44.1277
    },
    "location": {
      "sublocation": "Al-Aridah",
      "city": "Najran",
      "state": "Najran Province",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:02:14 09:45:28",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "UNEOM professional uniforms serving Najran in Najran Province, Saudi Arabia."
  },
  "cities/hero-riyadh": {
    "slug": "hero-riyadh",
    "category": "cities",
    "subCategory": null,
    "industry": null,
    "city": "riyadh",
    "path": "/images/cities/hero-riyadh.avif",
    "width": 1920,
    "height": 800,
    "variants": [
      {
        "width": 640,
        "height": 267,
        "path": "/images/cities/hero-riyadh-640.avif"
      },
      {
        "width": 960,
        "height": 400,
        "path": "/images/cities/hero-riyadh-960.avif"
      },
      {
        "width": 1440,
        "height": 600,
        "path": "/images/cities/hero-riyadh-1440.avif"
      }
    ],
    "webp": "/images/cities/hero-riyadh.webp",
    "description": "UNEOM professional uniforms in Riyadh, Riyadh Province, Saudi Arabia",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "Riyadh",
      "Riyadh Province"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "Diplomatic Quarter",
      "city": "Riyadh",
      "state": "Riyadh Province",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2026:04:28 18:36:55",
    "creatorTool": "UNEOM Design Lab",
    "alt": "UNEOM professional uniforms serving Riyadh in Riyadh Province, Saudi Arabia."
  },
  "cities/hero-sakaka": {
    "slug": "hero-sakaka",
    "category": "cities",
    "subCategory": null,
    "industry": null,
    "city": "sakaka",
    "path": "/images/cities/hero-sakaka.avif",
    "width": 1920,
    "height": 800,
    "variants": [
      {
        "width": 640,
        "height": 267,
        "path": "/images/cities/hero-sakaka-640.avif"
      },
      {
        "width": 960,
        "height": 400,
        "path": "/images/cities/hero-sakaka-960.avif"
      },
      {
        "width": 1440,
        "height": 600,
        "path": "/images/cities/hero-sakaka-1440.avif"
      }
    ],
    "webp": "/images/cities/hero-sakaka.webp",
    "description": "UNEOM professional uniforms in Sakaka, Al-Jouf Province, Saudi Arabia",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "Sakaka",
      "Al-Jouf Province"
    ],
    "gps": {
      "lat": 29.9697,
      "lng": 40.2064
    },
    "location": {
      "sublocation": "Al-Tuwair",
      "city": "Sakaka",
      "state": "Al-Jouf Province",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:10:01 18:23:18",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "UNEOM professional uniforms serving Sakaka in Al-Jouf Province, Saudi Arabia."
  },
  "cities/hero-tabuk": {
    "slug": "hero-tabuk",
    "category": "cities",
    "subCategory": null,
    "industry": null,
    "city": "tabuk",
    "path": "/images/cities/hero-tabuk.avif",
    "width": 1920,
    "height": 800,
    "variants": [
      {
        "width": 640,
        "height": 267,
        "path": "/images/cities/hero-tabuk-640.avif"
      },
      {
        "width": 960,
        "height": 400,
        "path": "/images/cities/hero-tabuk-960.avif"
      },
      {
        "width": 1440,
        "height": 600,
        "path": "/images/cities/hero-tabuk-1440.avif"
      }
    ],
    "webp": "/images/cities/hero-tabuk.webp",
    "description": "UNEOM professional uniforms in Tabuk, Tabuk Province, Saudi Arabia",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "Tabuk",
      "Tabuk Province"
    ],
    "gps": {
      "lat": 28.3835,
      "lng": 36.5662
    },
    "location": {
      "sublocation": "Old Castle Quarter",
      "city": "Tabuk",
      "state": "Tabuk Province",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:10:21 15:27:58",
    "creatorTool": "UNEOM Creative Department",
    "alt": "UNEOM professional uniforms serving Tabuk in Tabuk Province, Saudi Arabia."
  },
  "cities/hero-taif": {
    "slug": "hero-taif",
    "category": "cities",
    "subCategory": null,
    "industry": null,
    "city": "taif",
    "path": "/images/cities/hero-taif.avif",
    "width": 1920,
    "height": 800,
    "variants": [
      {
        "width": 640,
        "height": 267,
        "path": "/images/cities/hero-taif-640.avif"
      },
      {
        "width": 960,
        "height": 400,
        "path": "/images/cities/hero-taif-960.avif"
      },
      {
        "width": 1440,
        "height": 600,
        "path": "/images/cities/hero-taif-1440.avif"
      }
    ],
    "webp": "/images/cities/hero-taif.webp",
    "description": "UNEOM professional uniforms in Taif, Makkah Province, Saudi Arabia",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "Taif",
      "Makkah Province"
    ],
    "gps": {
      "lat": 21.2703,
      "lng": 40.4178
    },
    "location": {
      "sublocation": "Al-Hada",
      "city": "Taif",
      "state": "Makkah Province",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:02:12 11:18:18",
    "creatorTool": "UNEOM Editorial Pipeline",
    "alt": "UNEOM professional uniforms serving Taif in Makkah Province, Saudi Arabia."
  },
  "cities/hero-wadi-al-dawasir": {
    "slug": "hero-wadi-al-dawasir",
    "category": "cities",
    "subCategory": null,
    "industry": null,
    "city": "wadi-al-dawasir",
    "path": "/images/cities/hero-wadi-al-dawasir.avif",
    "width": 1920,
    "height": 800,
    "variants": [
      {
        "width": 640,
        "height": 267,
        "path": "/images/cities/hero-wadi-al-dawasir-640.avif"
      },
      {
        "width": 960,
        "height": 400,
        "path": "/images/cities/hero-wadi-al-dawasir-960.avif"
      },
      {
        "width": 1440,
        "height": 600,
        "path": "/images/cities/hero-wadi-al-dawasir-1440.avif"
      }
    ],
    "webp": "/images/cities/hero-wadi-al-dawasir.webp",
    "description": "UNEOM professional uniforms in Wadi Al-Dawasir, Riyadh Province, Saudi Arabia",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "Wadi Al-Dawasir",
      "Riyadh Province"
    ],
    "gps": {
      "lat": 20.4946,
      "lng": 44.8044
    },
    "location": {
      "sublocation": "Al-Qariyah",
      "city": "Wadi Al-Dawasir",
      "state": "Riyadh Province",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:06:10 16:08:40",
    "creatorTool": "UNEOM Production House",
    "alt": "UNEOM professional uniforms serving Wadi Al-Dawasir in Riyadh Province, Saudi Arabia."
  },
  "cities/hero-yanbu": {
    "slug": "hero-yanbu",
    "category": "cities",
    "subCategory": null,
    "industry": null,
    "city": "yanbu",
    "path": "/images/cities/hero-yanbu.avif",
    "width": 1920,
    "height": 800,
    "variants": [
      {
        "width": 640,
        "height": 267,
        "path": "/images/cities/hero-yanbu-640.avif"
      },
      {
        "width": 960,
        "height": 400,
        "path": "/images/cities/hero-yanbu-960.avif"
      },
      {
        "width": 1440,
        "height": 600,
        "path": "/images/cities/hero-yanbu-1440.avif"
      }
    ],
    "webp": "/images/cities/hero-yanbu.webp",
    "description": "UNEOM professional uniforms in Yanbu, Madinah Province, Saudi Arabia",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "Yanbu",
      "Madinah Province"
    ],
    "gps": {
      "lat": 24.0894,
      "lng": 38.0618
    },
    "location": {
      "sublocation": "Al-Nawah",
      "city": "Yanbu",
      "state": "Madinah Province",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:11:28 11:08:51",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "UNEOM professional uniforms serving Yanbu in Madinah Province, Saudi Arabia."
  }
};
