/**
 * Image Registry — fabrics category
 * Auto-generated by scripts/split-images-registry.mjs
 * 8 entries
 */

import type { ImageMetadata } from './types';

export const IMAGES_FABRICS: Record<string, ImageMetadata> = {
  "fabrics/cotton-spandex-twill-macro": {
    "slug": "cotton-spandex-twill-macro",
    "category": "fabrics",
    "subCategory": null,
    "industry": null,
    "city": "riyadh",
    "path": "/images/fabrics/cotton-spandex-twill-macro.avif",
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "height": 400,
        "path": "/images/fabrics/cotton-spandex-twill-macro-400.avif"
      },
      {
        "width": 800,
        "height": 800,
        "path": "/images/fabrics/cotton-spandex-twill-macro-800.avif"
      }
    ],
    "webp": "/images/fabrics/cotton-spandex-twill-macro.webp",
    "description": "UNEOM fabric macro detail — UNEOM textile catalog",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "textile",
      "fabric",
      "material macro",
      "OEKO-TEX"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:03:27 08:44:11",
    "creatorTool": "UNEOM Design Lab",
    "alt": "Fabric macro: cotton spandex twill — UNEOM textile catalog."
  },
  "fabrics/egyptian-cotton-poplin-macro": {
    "slug": "egyptian-cotton-poplin-macro",
    "category": "fabrics",
    "subCategory": null,
    "industry": null,
    "city": "riyadh",
    "path": "/images/fabrics/egyptian-cotton-poplin-macro.avif",
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "height": 400,
        "path": "/images/fabrics/egyptian-cotton-poplin-macro-400.avif"
      },
      {
        "width": 800,
        "height": 800,
        "path": "/images/fabrics/egyptian-cotton-poplin-macro-800.avif"
      }
    ],
    "webp": "/images/fabrics/egyptian-cotton-poplin-macro.webp",
    "description": "UNEOM fabric macro detail — UNEOM textile catalog",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "textile",
      "fabric",
      "material macro",
      "OEKO-TEX"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:03:19 10:16:19",
    "creatorTool": "UNEOM Editorial Pipeline",
    "alt": "Fabric macro: egyptian cotton poplin — UNEOM textile catalog."
  },
  "fabrics/hrc2-fr-cotton-macro": {
    "slug": "hrc2-fr-cotton-macro",
    "category": "fabrics",
    "subCategory": null,
    "industry": "manufacturing",
    "city": "al-jubail",
    "path": "/images/fabrics/hrc2-fr-cotton-macro.avif",
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "height": 400,
        "path": "/images/fabrics/hrc2-fr-cotton-macro-400.avif"
      },
      {
        "width": 800,
        "height": 800,
        "path": "/images/fabrics/hrc2-fr-cotton-macro-800.avif"
      }
    ],
    "webp": "/images/fabrics/hrc2-fr-cotton-macro.webp",
    "description": "UNEOM fabric macro detail — UNEOM textile catalog",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "industrial uniforms",
      "FR coveralls",
      "PPE",
      "HCIS compliant",
      "workwear",
      "textile",
      "fabric",
      "material macro"
    ],
    "gps": {
      "lat": 27.0046,
      "lng": 49.661
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:09:21 18:11:10",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "Fabric macro: hrc2 fr cotton — UNEOM textile catalog."
  },
  "fabrics/oeko-tex-bamboo-blend-macro": {
    "slug": "oeko-tex-bamboo-blend-macro",
    "category": "fabrics",
    "subCategory": null,
    "industry": null,
    "city": "riyadh",
    "path": "/images/fabrics/oeko-tex-bamboo-blend-macro.avif",
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "height": 400,
        "path": "/images/fabrics/oeko-tex-bamboo-blend-macro-400.avif"
      },
      {
        "width": 800,
        "height": 800,
        "path": "/images/fabrics/oeko-tex-bamboo-blend-macro-800.avif"
      }
    ],
    "webp": "/images/fabrics/oeko-tex-bamboo-blend-macro.webp",
    "description": "UNEOM fabric macro detail — UNEOM textile catalog",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "textile",
      "fabric",
      "material macro",
      "OEKO-TEX"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:02:25 12:38:23",
    "creatorTool": "UNEOM Creative Department",
    "alt": "Fabric macro: oeko tex bamboo blend — UNEOM textile catalog."
  },
  "fabrics/performance-poly-macro": {
    "slug": "performance-poly-macro",
    "category": "fabrics",
    "subCategory": null,
    "industry": null,
    "city": "riyadh",
    "path": "/images/fabrics/performance-poly-macro.avif",
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "height": 400,
        "path": "/images/fabrics/performance-poly-macro-400.avif"
      },
      {
        "width": 800,
        "height": 800,
        "path": "/images/fabrics/performance-poly-macro-800.avif"
      }
    ],
    "webp": "/images/fabrics/performance-poly-macro.webp",
    "description": "UNEOM fabric macro detail — UNEOM textile catalog",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "textile",
      "fabric",
      "material macro",
      "OEKO-TEX"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2026:04:23 13:11:03",
    "creatorTool": "UNEOM Creative Department",
    "alt": "Fabric macro: performance poly — UNEOM textile catalog."
  },
  "fabrics/poly-cotton-65-35-macro": {
    "slug": "poly-cotton-65-35-macro",
    "category": "fabrics",
    "subCategory": null,
    "industry": null,
    "city": "riyadh",
    "path": "/images/fabrics/poly-cotton-65-35-macro.avif",
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "height": 400,
        "path": "/images/fabrics/poly-cotton-65-35-macro-400.avif"
      },
      {
        "width": 800,
        "height": 800,
        "path": "/images/fabrics/poly-cotton-65-35-macro-800.avif"
      }
    ],
    "webp": "/images/fabrics/poly-cotton-65-35-macro.webp",
    "description": "UNEOM fabric macro detail — UNEOM textile catalog",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "textile",
      "fabric",
      "material macro",
      "OEKO-TEX"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:12:24 08:22:07",
    "creatorTool": "UNEOM Production House",
    "alt": "Fabric macro: poly cotton 65 35 — UNEOM textile catalog."
  },
  "fabrics/reflective-hi-vis-poly-macro": {
    "slug": "reflective-hi-vis-poly-macro",
    "category": "fabrics",
    "subCategory": null,
    "industry": null,
    "city": "riyadh",
    "path": "/images/fabrics/reflective-hi-vis-poly-macro.avif",
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "height": 400,
        "path": "/images/fabrics/reflective-hi-vis-poly-macro-400.avif"
      },
      {
        "width": 800,
        "height": 800,
        "path": "/images/fabrics/reflective-hi-vis-poly-macro-800.avif"
      }
    ],
    "webp": "/images/fabrics/reflective-hi-vis-poly-macro.webp",
    "description": "UNEOM fabric macro detail — UNEOM textile catalog",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "textile",
      "fabric",
      "material macro",
      "OEKO-TEX"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:08:19 12:56:42",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "Fabric macro: reflective hi vis poly — UNEOM textile catalog."
  },
  "fabrics/wool-poly-blend-macro": {
    "slug": "wool-poly-blend-macro",
    "category": "fabrics",
    "subCategory": null,
    "industry": null,
    "city": "riyadh",
    "path": "/images/fabrics/wool-poly-blend-macro.avif",
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "height": 400,
        "path": "/images/fabrics/wool-poly-blend-macro-400.avif"
      },
      {
        "width": 800,
        "height": 800,
        "path": "/images/fabrics/wool-poly-blend-macro-800.avif"
      }
    ],
    "webp": "/images/fabrics/wool-poly-blend-macro.webp",
    "description": "UNEOM fabric macro detail — UNEOM textile catalog",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "textile",
      "fabric",
      "material macro",
      "OEKO-TEX"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:11:13 14:11:07",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "Fabric macro: wool poly blend — UNEOM textile catalog."
  }
};
