/**
 * Image Registry — heroes category
 * Auto-generated by scripts/split-images-registry.mjs
 * 8 entries
 */

import type { ImageMetadata } from './types';

export const IMAGES_HEROES: Record<string, ImageMetadata> = {
  "heroes/aviation-pillar-hero": {
    "slug": "aviation-pillar-hero",
    "category": "heroes",
    "subCategory": null,
    "industry": "aviation",
    "city": "jeddah",
    "path": "/images/heroes/aviation-pillar-hero.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/heroes/aviation-pillar-hero-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/heroes/aviation-pillar-hero-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/heroes/aviation-pillar-hero-1440.avif"
      }
    ],
    "webp": "/images/heroes/aviation-pillar-hero.webp",
    "description": "UNEOM Aviation uniforms — Saudi Arabia industry leader",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "aviation uniforms",
      "airline crew",
      "ground staff",
      "GACA compliant"
    ],
    "gps": {
      "lat": 21.4858,
      "lng": 39.1925
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:02:05 18:46:27",
    "creatorTool": "UNEOM Editorial Pipeline",
    "alt": "UNEOM Aviation uniforms — Saudi B2B leader in aviation attire."
  },
  "heroes/corporate-pillar-hero": {
    "slug": "corporate-pillar-hero",
    "category": "heroes",
    "subCategory": null,
    "industry": "corporate",
    "city": "riyadh",
    "path": "/images/heroes/corporate-pillar-hero.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/heroes/corporate-pillar-hero-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/heroes/corporate-pillar-hero-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/heroes/corporate-pillar-hero-1440.avif"
      }
    ],
    "webp": "/images/heroes/corporate-pillar-hero.webp",
    "description": "UNEOM Corporate uniforms — Saudi Arabia industry leader",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "corporate workwear",
      "business attire",
      "executive uniforms",
      "office wear"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:07:12 14:46:52",
    "creatorTool": "UNEOM Editorial Pipeline",
    "alt": "UNEOM Corporate uniforms — Saudi B2B leader in corporate attire."
  },
  "heroes/education-pillar-hero": {
    "slug": "education-pillar-hero",
    "category": "heroes",
    "subCategory": null,
    "industry": "education",
    "city": "riyadh",
    "path": "/images/heroes/education-pillar-hero.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/heroes/education-pillar-hero-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/heroes/education-pillar-hero-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/heroes/education-pillar-hero-1440.avif"
      }
    ],
    "webp": "/images/heroes/education-pillar-hero.webp",
    "description": "UNEOM Education uniforms — Saudi Arabia industry leader",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "school uniforms",
      "student attire",
      "education sector",
      "MoE compliant"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:11:01 14:16:15",
    "creatorTool": "UNEOM Creative Department",
    "alt": "UNEOM Education uniforms — Saudi B2B leader in education attire."
  },
  "heroes/healthcare-pillar-hero": {
    "slug": "healthcare-pillar-hero",
    "category": "heroes",
    "subCategory": null,
    "industry": "healthcare",
    "city": "riyadh",
    "path": "/images/heroes/healthcare-pillar-hero.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/heroes/healthcare-pillar-hero-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/heroes/healthcare-pillar-hero-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/heroes/healthcare-pillar-hero-1440.avif"
      }
    ],
    "webp": "/images/heroes/healthcare-pillar-hero.webp",
    "description": "UNEOM Healthcare uniforms — Saudi Arabia industry leader",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "medical scrubs",
      "healthcare uniforms",
      "hospital attire",
      "MoH compliant"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:02:24 12:19:23",
    "creatorTool": "UNEOM Production House",
    "alt": "UNEOM Healthcare uniforms — Saudi B2B leader in healthcare attire."
  },
  "heroes/hospitality-pillar-hero": {
    "slug": "hospitality-pillar-hero",
    "category": "heroes",
    "subCategory": null,
    "industry": "hospitality",
    "city": "jeddah",
    "path": "/images/heroes/hospitality-pillar-hero.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/heroes/hospitality-pillar-hero-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/heroes/hospitality-pillar-hero-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/heroes/hospitality-pillar-hero-1440.avif"
      }
    ],
    "webp": "/images/heroes/hospitality-pillar-hero.webp",
    "description": "UNEOM Hospitality uniforms — Saudi Arabia industry leader",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "hospitality uniforms",
      "hotel staff",
      "F&B uniforms",
      "luxury service"
    ],
    "gps": {
      "lat": 21.4858,
      "lng": 39.1925
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:05:06 10:51:49",
    "creatorTool": "UNEOM Creative Department",
    "alt": "UNEOM Hospitality uniforms — Saudi B2B leader in hospitality attire."
  },
  "heroes/manufacturing-pillar-hero": {
    "slug": "manufacturing-pillar-hero",
    "category": "heroes",
    "subCategory": null,
    "industry": "manufacturing",
    "city": "al-jubail",
    "path": "/images/heroes/manufacturing-pillar-hero.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/heroes/manufacturing-pillar-hero-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/heroes/manufacturing-pillar-hero-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/heroes/manufacturing-pillar-hero-1440.avif"
      }
    ],
    "webp": "/images/heroes/manufacturing-pillar-hero.webp",
    "description": "UNEOM Manufacturing uniforms — Saudi Arabia industry leader",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "industrial uniforms",
      "FR coveralls",
      "PPE",
      "HCIS compliant",
      "workwear"
    ],
    "gps": {
      "lat": 27.0046,
      "lng": 49.661
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:03:01 14:39:17",
    "creatorTool": "UNEOM Editorial Pipeline",
    "alt": "UNEOM Manufacturing uniforms — Saudi B2B leader in manufacturing attire."
  },
  "heroes/retail-pillar-hero": {
    "slug": "retail-pillar-hero",
    "category": "heroes",
    "subCategory": null,
    "industry": "retail",
    "city": "riyadh",
    "path": "/images/heroes/retail-pillar-hero.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/heroes/retail-pillar-hero-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/heroes/retail-pillar-hero-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/heroes/retail-pillar-hero-1440.avif"
      }
    ],
    "webp": "/images/heroes/retail-pillar-hero.webp",
    "description": "UNEOM Retail uniforms — Saudi Arabia industry leader",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "retail uniforms",
      "store staff",
      "shop attire",
      "branded workwear"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2026:03:29 18:42:53",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "UNEOM Retail uniforms — Saudi B2B leader in retail attire."
  },
  "heroes/security-pillar-hero": {
    "slug": "security-pillar-hero",
    "category": "heroes",
    "subCategory": null,
    "industry": "security",
    "city": "riyadh",
    "path": "/images/heroes/security-pillar-hero.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/heroes/security-pillar-hero-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/heroes/security-pillar-hero-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/heroes/security-pillar-hero-1440.avif"
      }
    ],
    "webp": "/images/heroes/security-pillar-hero.webp",
    "description": "UNEOM Security uniforms — Saudi Arabia industry leader",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "security uniforms",
      "tactical wear",
      "guard attire",
      "HCIS standards"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2026:03:30 13:02:30",
    "creatorTool": "UNEOM Creative Department",
    "alt": "UNEOM Security uniforms — Saudi B2B leader in security attire."
  }
};
