/**
 * Image Registry — Central index
 * Auto-generated by scripts/split-images-registry.mjs
 *
 * Re-exports the unified IMAGES lookup + types + helpers.
 * Each category is in its own file for tree-shaking.
 */

import { IMAGES_BLOG } from './blog';
import { IMAGES_CASE_STUDIES } from './case-studies';
import { IMAGES_CITIES } from './cities';
import { IMAGES_FABRICS } from './fabrics';
import { IMAGES_HEROES } from './heroes';
import { IMAGES_PROCESS } from './process';
import { IMAGES_PRODUCTS } from './products';
import { IMAGES_RESOURCES } from './resources';
import { IMAGES_TRUST } from './trust';

export type { ImageCategory, ImageVariant, ImageMetadata } from './types';
export { buildSrcSet, defaultSizes } from './types';

/** Unified image lookup — all categories merged */
export const IMAGES: Record<string, import('./types').ImageMetadata> = {
  ...IMAGES_BLOG,
  ...IMAGES_CASE_STUDIES,
  ...IMAGES_CITIES,
  ...IMAGES_FABRICS,
  ...IMAGES_HEROES,
  ...IMAGES_PROCESS,
  ...IMAGES_PRODUCTS,
  ...IMAGES_RESOURCES,
  ...IMAGES_TRUST
};
