/**
 * Image Registry — process category
 * Auto-generated by scripts/split-images-registry.mjs
 * 2 entries
 */

import type { ImageMetadata } from './types';

export const IMAGES_PROCESS: Record<string, ImageMetadata> = {
  "process/bulk-ordering": {
    "slug": "bulk-ordering",
    "category": "process",
    "subCategory": null,
    "industry": null,
    "city": "riyadh",
    "path": "/images/process/bulk-ordering.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/process/bulk-ordering-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/process/bulk-ordering-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/process/bulk-ordering-1440.avif"
      }
    ],
    "webp": "/images/process/bulk-ordering.webp",
    "description": "UNEOM process workflow — bulk ordering",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:10:09 15:15:07",
    "creatorTool": "UNEOM Design Lab",
    "alt": "UNEOM process diagram: bulk ordering."
  },
  "process/custom-design-workflow": {
    "slug": "custom-design-workflow",
    "category": "process",
    "subCategory": null,
    "industry": null,
    "city": "riyadh",
    "path": "/images/process/custom-design-workflow.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/process/custom-design-workflow-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/process/custom-design-workflow-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/process/custom-design-workflow-1440.avif"
      }
    ],
    "webp": "/images/process/custom-design-workflow.webp",
    "description": "UNEOM process workflow — custom design workflow",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:07:27 11:08:48",
    "creatorTool": "UNEOM Production House",
    "alt": "UNEOM process diagram: custom design workflow."
  }
};
