/**
 * Image Registry — products category
 * Auto-generated by scripts/split-images-registry.mjs
 * 16 entries
 */

import type { ImageMetadata } from './types';

export const IMAGES_PRODUCTS: Record<string, ImageMetadata> = {
  "products/aviation/airline-crew-uniform": {
    "slug": "airline-crew-uniform",
    "category": "products",
    "subCategory": "aviation",
    "industry": "aviation",
    "city": "jeddah",
    "path": "/images/products/aviation/airline-crew-uniform.avif",
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "height": 400,
        "path": "/images/products/aviation/airline-crew-uniform-400.avif"
      },
      {
        "width": 800,
        "height": 800,
        "path": "/images/products/aviation/airline-crew-uniform-800.avif"
      }
    ],
    "webp": "/images/products/aviation/airline-crew-uniform.webp",
    "description": "UNEOM Airline Crew Uniform in Wool-Polyester Blend — UNEOM Aviation line",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "aviation uniforms",
      "airline crew",
      "ground staff",
      "GACA compliant"
    ],
    "gps": {
      "lat": 21.4858,
      "lng": 39.1925
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2026:03:16 11:31:19",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "Airline Crew Uniform — UNEOM Aviation line, Wool-Polyester Blend."
  },
  "products/aviation/ground-staff-uniform": {
    "slug": "ground-staff-uniform",
    "category": "products",
    "subCategory": "aviation",
    "industry": "aviation",
    "city": "jeddah",
    "path": "/images/products/aviation/ground-staff-uniform.avif",
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "height": 400,
        "path": "/images/products/aviation/ground-staff-uniform-400.avif"
      },
      {
        "width": 800,
        "height": 800,
        "path": "/images/products/aviation/ground-staff-uniform-800.avif"
      }
    ],
    "webp": "/images/products/aviation/ground-staff-uniform.webp",
    "description": "UNEOM Ground Staff Uniform in Performance Polyester — UNEOM Aviation line",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "aviation uniforms",
      "airline crew",
      "ground staff",
      "GACA compliant"
    ],
    "gps": {
      "lat": 21.4858,
      "lng": 39.1925
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:10:17 11:41:58",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "Ground Staff Uniform — UNEOM Aviation line, Performance Polyester."
  },
  "products/corporate/business-shirt-set": {
    "slug": "business-shirt-set",
    "category": "products",
    "subCategory": "corporate",
    "industry": "corporate",
    "city": "riyadh",
    "path": "/images/products/corporate/business-shirt-set.avif",
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "height": 400,
        "path": "/images/products/corporate/business-shirt-set-400.avif"
      },
      {
        "width": 800,
        "height": 800,
        "path": "/images/products/corporate/business-shirt-set-800.avif"
      }
    ],
    "webp": "/images/products/corporate/business-shirt-set.webp",
    "description": "UNEOM Business Shirt Set in Egyptian Cotton Poplin — UNEOM Corporate line",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "corporate workwear",
      "business attire",
      "executive uniforms",
      "office wear"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2026:01:21 17:39:13",
    "creatorTool": "UNEOM Design Lab",
    "alt": "Business Shirt Set — UNEOM Corporate line, Egyptian Cotton Poplin."
  },
  "products/corporate/executive-suit": {
    "slug": "executive-suit",
    "category": "products",
    "subCategory": "corporate",
    "industry": "corporate",
    "city": "riyadh",
    "path": "/images/products/corporate/executive-suit.avif",
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "height": 400,
        "path": "/images/products/corporate/executive-suit-400.avif"
      },
      {
        "width": 800,
        "height": 800,
        "path": "/images/products/corporate/executive-suit-800.avif"
      }
    ],
    "webp": "/images/products/corporate/executive-suit.webp",
    "description": "UNEOM Executive Suit in Wool-Polyester Blend — UNEOM Corporate line",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "corporate workwear",
      "business attire",
      "executive uniforms",
      "office wear"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:05:15 08:16:56",
    "creatorTool": "UNEOM Editorial Pipeline",
    "alt": "Executive Suit — UNEOM Corporate line, Wool-Polyester Blend."
  },
  "products/education/student-uniform-boys": {
    "slug": "student-uniform-boys",
    "category": "products",
    "subCategory": "education",
    "industry": "education",
    "city": "riyadh",
    "path": "/images/products/education/student-uniform-boys.avif",
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "height": 400,
        "path": "/images/products/education/student-uniform-boys-400.avif"
      },
      {
        "width": 800,
        "height": 800,
        "path": "/images/products/education/student-uniform-boys-800.avif"
      }
    ],
    "webp": "/images/products/education/student-uniform-boys.webp",
    "description": "UNEOM Boys Student Uniform in Polyester-Cotton 65/35 — UNEOM Education line",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "school uniforms",
      "student attire",
      "education sector",
      "MoE compliant"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:04:03 15:05:11",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "Boys Student Uniform — UNEOM Education line, Polyester-Cotton 65/35."
  },
  "products/education/student-uniform-girls": {
    "slug": "student-uniform-girls",
    "category": "products",
    "subCategory": "education",
    "industry": "education",
    "city": "riyadh",
    "path": "/images/products/education/student-uniform-girls.avif",
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "height": 400,
        "path": "/images/products/education/student-uniform-girls-400.avif"
      },
      {
        "width": 800,
        "height": 800,
        "path": "/images/products/education/student-uniform-girls-800.avif"
      }
    ],
    "webp": "/images/products/education/student-uniform-girls.webp",
    "description": "UNEOM Girls Student Uniform in Polyester-Cotton 65/35 — UNEOM Education line",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "school uniforms",
      "student attire",
      "education sector",
      "MoE compliant"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:06:14 11:46:16",
    "creatorTool": "UNEOM Production House",
    "alt": "Girls Student Uniform — UNEOM Education line, Polyester-Cotton 65/35."
  },
  "products/hospitality-attire/chef-jacket-classic": {
    "slug": "chef-jacket-classic",
    "category": "products",
    "subCategory": "hospitality-attire",
    "industry": "hospitality",
    "city": "jeddah",
    "path": "/images/products/hospitality-attire/chef-jacket-classic.avif",
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "height": 400,
        "path": "/images/products/hospitality-attire/chef-jacket-classic-400.avif"
      },
      {
        "width": 800,
        "height": 800,
        "path": "/images/products/hospitality-attire/chef-jacket-classic-800.avif"
      }
    ],
    "webp": "/images/products/hospitality-attire/chef-jacket-classic.webp",
    "description": "UNEOM Classic Chef Jacket in Heavy Cotton — UNEOM Hospitality line",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "hospitality uniforms",
      "hotel staff",
      "F&B uniforms",
      "luxury service"
    ],
    "gps": {
      "lat": 21.4858,
      "lng": 39.1925
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:01:04 16:14:26",
    "creatorTool": "UNEOM Design Lab",
    "alt": "Classic Chef Jacket — UNEOM Hospitality line, Heavy Cotton."
  },
  "products/hospitality-attire/hotel-front-desk": {
    "slug": "hotel-front-desk",
    "category": "products",
    "subCategory": "hospitality-attire",
    "industry": "hospitality",
    "city": "jeddah",
    "path": "/images/products/hospitality-attire/hotel-front-desk.avif",
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "height": 400,
        "path": "/images/products/hospitality-attire/hotel-front-desk-400.avif"
      },
      {
        "width": 800,
        "height": 800,
        "path": "/images/products/hospitality-attire/hotel-front-desk-800.avif"
      }
    ],
    "webp": "/images/products/hospitality-attire/hotel-front-desk.webp",
    "description": "UNEOM Hotel Front Desk Uniform in Wool-Polyester Blend — UNEOM Hospitality line",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "hospitality uniforms",
      "hotel staff",
      "F&B uniforms",
      "luxury service"
    ],
    "gps": {
      "lat": 21.4858,
      "lng": 39.1925
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2026:04:07 09:08:11",
    "creatorTool": "UNEOM Creative Department",
    "alt": "Hotel Front Desk Uniform — UNEOM Hospitality line, Wool-Polyester Blend."
  },
  "products/hospitality-attire/housekeeping-set": {
    "slug": "housekeeping-set",
    "category": "products",
    "subCategory": "hospitality-attire",
    "industry": "hospitality",
    "city": "jeddah",
    "path": "/images/products/hospitality-attire/housekeeping-set.avif",
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "height": 400,
        "path": "/images/products/hospitality-attire/housekeeping-set-400.avif"
      },
      {
        "width": 800,
        "height": 800,
        "path": "/images/products/hospitality-attire/housekeeping-set-800.avif"
      }
    ],
    "webp": "/images/products/hospitality-attire/housekeeping-set.webp",
    "description": "UNEOM Housekeeping Set in Cotton-Spandex Twill — UNEOM Hospitality line",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "hospitality uniforms",
      "hotel staff",
      "F&B uniforms",
      "luxury service"
    ],
    "gps": {
      "lat": 21.4858,
      "lng": 39.1925
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:02:21 11:02:53",
    "creatorTool": "UNEOM Design Lab",
    "alt": "Housekeeping Set — UNEOM Hospitality line, Cotton-Spandex Twill."
  },
  "products/manufacturing/coverall-fr": {
    "slug": "coverall-fr",
    "category": "products",
    "subCategory": "manufacturing",
    "industry": "manufacturing",
    "city": "al-jubail",
    "path": "/images/products/manufacturing/coverall-fr.avif",
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "height": 400,
        "path": "/images/products/manufacturing/coverall-fr-400.avif"
      },
      {
        "width": 800,
        "height": 800,
        "path": "/images/products/manufacturing/coverall-fr-800.avif"
      }
    ],
    "webp": "/images/products/manufacturing/coverall-fr.webp",
    "description": "UNEOM FR Coverall in HRC2 FR Cotton — UNEOM Manufacturing line",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "industrial uniforms",
      "FR coveralls",
      "PPE",
      "HCIS compliant",
      "workwear"
    ],
    "gps": {
      "lat": 27.0046,
      "lng": 49.661
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2026:01:13 15:07:23",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "FR Coverall — UNEOM Manufacturing line, HRC2 FR Cotton."
  },
  "products/manufacturing/hi-vis-jacket": {
    "slug": "hi-vis-jacket",
    "category": "products",
    "subCategory": "manufacturing",
    "industry": "manufacturing",
    "city": "al-jubail",
    "path": "/images/products/manufacturing/hi-vis-jacket.avif",
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "height": 400,
        "path": "/images/products/manufacturing/hi-vis-jacket-400.avif"
      },
      {
        "width": 800,
        "height": 800,
        "path": "/images/products/manufacturing/hi-vis-jacket-800.avif"
      }
    ],
    "webp": "/images/products/manufacturing/hi-vis-jacket.webp",
    "description": "UNEOM Hi-Vis Jacket in Reflective Hi-Vis Polyester — UNEOM Manufacturing line",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "industrial uniforms",
      "FR coveralls",
      "PPE",
      "HCIS compliant",
      "workwear"
    ],
    "gps": {
      "lat": 27.0046,
      "lng": 49.661
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2026:03:26 13:20:53",
    "creatorTool": "UNEOM Editorial Pipeline",
    "alt": "Hi-Vis Jacket — UNEOM Manufacturing line, Reflective Hi-Vis Polyester."
  },
  "products/medical-scrubs/lab-coat-doctor": {
    "slug": "lab-coat-doctor",
    "category": "products",
    "subCategory": "medical-scrubs",
    "industry": "healthcare",
    "city": "riyadh",
    "path": "/images/products/medical-scrubs/lab-coat-doctor.avif",
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "height": 400,
        "path": "/images/products/medical-scrubs/lab-coat-doctor-400.avif"
      },
      {
        "width": 800,
        "height": 800,
        "path": "/images/products/medical-scrubs/lab-coat-doctor-800.avif"
      }
    ],
    "webp": "/images/products/medical-scrubs/lab-coat-doctor.webp",
    "description": "UNEOM Doctor Lab Coat in Egyptian Cotton Poplin — UNEOM Healthcare line",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "medical scrubs",
      "healthcare uniforms",
      "hospital attire",
      "MoH compliant"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:01:05 12:22:14",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "Doctor Lab Coat — UNEOM Healthcare line, Egyptian Cotton Poplin."
  },
  "products/medical-scrubs/scrub-set-classic": {
    "slug": "scrub-set-classic",
    "category": "products",
    "subCategory": "medical-scrubs",
    "industry": "healthcare",
    "city": "riyadh",
    "path": "/images/products/medical-scrubs/scrub-set-classic.avif",
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "height": 400,
        "path": "/images/products/medical-scrubs/scrub-set-classic-400.avif"
      },
      {
        "width": 800,
        "height": 800,
        "path": "/images/products/medical-scrubs/scrub-set-classic-800.avif"
      }
    ],
    "webp": "/images/products/medical-scrubs/scrub-set-classic.webp",
    "description": "UNEOM Classic Medical Scrub Set in Polyester-Cotton 65/35 — UNEOM Healthcare line",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "medical scrubs",
      "healthcare uniforms",
      "hospital attire",
      "MoH compliant"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:07:09 11:50:05",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "Classic Medical Scrub Set — UNEOM Healthcare line, Polyester-Cotton 65/35."
  },
  "products/retail/staff-polo": {
    "slug": "staff-polo",
    "category": "products",
    "subCategory": "retail",
    "industry": "retail",
    "city": "riyadh",
    "path": "/images/products/retail/staff-polo.avif",
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "height": 400,
        "path": "/images/products/retail/staff-polo-400.avif"
      },
      {
        "width": 800,
        "height": 800,
        "path": "/images/products/retail/staff-polo-800.avif"
      }
    ],
    "webp": "/images/products/retail/staff-polo.webp",
    "description": "UNEOM product image — UNEOM Retail",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "retail uniforms",
      "store staff",
      "shop attire",
      "branded workwear"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:11:15 16:26:24",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "UNEOM Retail product — staff polo."
  },
  "products/security/guard-uniform-classic": {
    "slug": "guard-uniform-classic",
    "category": "products",
    "subCategory": "security",
    "industry": "security",
    "city": "riyadh",
    "path": "/images/products/security/guard-uniform-classic.avif",
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "height": 400,
        "path": "/images/products/security/guard-uniform-classic-400.avif"
      },
      {
        "width": 800,
        "height": 800,
        "path": "/images/products/security/guard-uniform-classic-800.avif"
      }
    ],
    "webp": "/images/products/security/guard-uniform-classic.webp",
    "description": "UNEOM Classic Guard Uniform in Polyester-Cotton 65/35 — UNEOM Security line",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "security uniforms",
      "tactical wear",
      "guard attire",
      "HCIS standards"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:03:11 18:42:39",
    "creatorTool": "UNEOM Production House",
    "alt": "Classic Guard Uniform — UNEOM Security line, Polyester-Cotton 65/35."
  },
  "products/security/tactical-set": {
    "slug": "tactical-set",
    "category": "products",
    "subCategory": "security",
    "industry": "security",
    "city": "riyadh",
    "path": "/images/products/security/tactical-set.avif",
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "height": 400,
        "path": "/images/products/security/tactical-set-400.avif"
      },
      {
        "width": 800,
        "height": 800,
        "path": "/images/products/security/tactical-set-800.avif"
      }
    ],
    "webp": "/images/products/security/tactical-set.webp",
    "description": "UNEOM product image — UNEOM Security",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "security uniforms",
      "tactical wear",
      "guard attire",
      "HCIS standards"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:07:22 16:59:59",
    "creatorTool": "UNEOM Design Lab",
    "alt": "UNEOM Security product — tactical set."
  }
};
