/**
 * Image Registry — resources category
 * Auto-generated by scripts/split-images-registry.mjs
 * 12 entries
 */

import type { ImageMetadata } from './types';

export const IMAGES_RESOURCES: Record<string, ImageMetadata> = {
  "resources/cleanroom-best-practices-hero": {
    "slug": "cleanroom-best-practices-hero",
    "category": "resources",
    "subCategory": null,
    "industry": null,
    "city": "riyadh",
    "path": "/images/resources/cleanroom-best-practices-hero.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/resources/cleanroom-best-practices-hero-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/resources/cleanroom-best-practices-hero-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/resources/cleanroom-best-practices-hero-1440.avif"
      }
    ],
    "webp": "/images/resources/cleanroom-best-practices-hero.webp",
    "description": "UNEOM resource guide — cleanroom best practices",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:11:22 17:59:11",
    "creatorTool": "UNEOM Production House",
    "alt": "Resource guide: cleanroom best practices — UNEOM expertise."
  },
  "resources/electrical-safety-ppe-hero": {
    "slug": "electrical-safety-ppe-hero",
    "category": "resources",
    "subCategory": null,
    "industry": "manufacturing",
    "city": "al-jubail",
    "path": "/images/resources/electrical-safety-ppe-hero.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/resources/electrical-safety-ppe-hero-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/resources/electrical-safety-ppe-hero-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/resources/electrical-safety-ppe-hero-1440.avif"
      }
    ],
    "webp": "/images/resources/electrical-safety-ppe-hero.webp",
    "description": "UNEOM resource guide — electrical safety ppe",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "industrial uniforms",
      "FR coveralls",
      "PPE",
      "HCIS compliant",
      "workwear"
    ],
    "gps": {
      "lat": 27.0046,
      "lng": 49.661
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2026:04:12 15:13:15",
    "creatorTool": "UNEOM Design Lab",
    "alt": "Resource guide: electrical safety ppe — UNEOM expertise."
  },
  "resources/fabric-guide-hero": {
    "slug": "fabric-guide-hero",
    "category": "resources",
    "subCategory": null,
    "industry": null,
    "city": "riyadh",
    "path": "/images/resources/fabric-guide-hero.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/resources/fabric-guide-hero-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/resources/fabric-guide-hero-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/resources/fabric-guide-hero-1440.avif"
      }
    ],
    "webp": "/images/resources/fabric-guide-hero.webp",
    "description": "UNEOM resource guide — fabric guide",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:12:10 12:11:32",
    "creatorTool": "UNEOM Editorial Pipeline",
    "alt": "Resource guide: fabric guide — UNEOM expertise."
  },
  "resources/healthcare-uniform-standards-hero": {
    "slug": "healthcare-uniform-standards-hero",
    "category": "resources",
    "subCategory": null,
    "industry": "healthcare",
    "city": "riyadh",
    "path": "/images/resources/healthcare-uniform-standards-hero.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/resources/healthcare-uniform-standards-hero-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/resources/healthcare-uniform-standards-hero-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/resources/healthcare-uniform-standards-hero-1440.avif"
      }
    ],
    "webp": "/images/resources/healthcare-uniform-standards-hero.webp",
    "description": "UNEOM resource guide — healthcare uniform standards",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "medical scrubs",
      "healthcare uniforms",
      "hospital attire",
      "MoH compliant"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:12:11 12:33:04",
    "creatorTool": "UNEOM Editorial Pipeline",
    "alt": "Resource guide: healthcare uniform standards — UNEOM expertise."
  },
  "resources/nursing-uniform-guide-hero": {
    "slug": "nursing-uniform-guide-hero",
    "category": "resources",
    "subCategory": null,
    "industry": "healthcare",
    "city": "riyadh",
    "path": "/images/resources/nursing-uniform-guide-hero.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/resources/nursing-uniform-guide-hero-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/resources/nursing-uniform-guide-hero-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/resources/nursing-uniform-guide-hero-1440.avif"
      }
    ],
    "webp": "/images/resources/nursing-uniform-guide-hero.webp",
    "description": "UNEOM resource guide — nursing uniform guide",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "medical scrubs",
      "healthcare uniforms",
      "hospital attire",
      "MoH compliant"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:05:15 08:15:07",
    "creatorTool": "UNEOM Editorial Pipeline",
    "alt": "Resource guide: nursing uniform guide — UNEOM expertise."
  },
  "resources/policy-templates-hero": {
    "slug": "policy-templates-hero",
    "category": "resources",
    "subCategory": null,
    "industry": null,
    "city": "riyadh",
    "path": "/images/resources/policy-templates-hero.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/resources/policy-templates-hero-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/resources/policy-templates-hero-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/resources/policy-templates-hero-1440.avif"
      }
    ],
    "webp": "/images/resources/policy-templates-hero.webp",
    "description": "UNEOM resource guide — policy templates",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:04:14 14:32:58",
    "creatorTool": "UNEOM Design Lab",
    "alt": "Resource guide: policy templates — UNEOM expertise."
  },
  "resources/procurement-guide-hero": {
    "slug": "procurement-guide-hero",
    "category": "resources",
    "subCategory": null,
    "industry": null,
    "city": "riyadh",
    "path": "/images/resources/procurement-guide-hero.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/resources/procurement-guide-hero-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/resources/procurement-guide-hero-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/resources/procurement-guide-hero-1440.avif"
      }
    ],
    "webp": "/images/resources/procurement-guide-hero.webp",
    "description": "UNEOM resource guide — procurement guide",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:09:14 09:28:48",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "Resource guide: procurement guide — UNEOM expertise."
  },
  "resources/professional-security-standards-hero": {
    "slug": "professional-security-standards-hero",
    "category": "resources",
    "subCategory": null,
    "industry": "security",
    "city": "riyadh",
    "path": "/images/resources/professional-security-standards-hero.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/resources/professional-security-standards-hero-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/resources/professional-security-standards-hero-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/resources/professional-security-standards-hero-1440.avif"
      }
    ],
    "webp": "/images/resources/professional-security-standards-hero.webp",
    "description": "UNEOM resource guide — professional security standards",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "security uniforms",
      "tactical wear",
      "guard attire",
      "HCIS standards"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:10:14 08:32:56",
    "creatorTool": "UNEOM Editorial Pipeline",
    "alt": "Resource guide: professional security standards — UNEOM expertise."
  },
  "resources/security-equipment-standards-hero": {
    "slug": "security-equipment-standards-hero",
    "category": "resources",
    "subCategory": null,
    "industry": "security",
    "city": "riyadh",
    "path": "/images/resources/security-equipment-standards-hero.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/resources/security-equipment-standards-hero-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/resources/security-equipment-standards-hero-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/resources/security-equipment-standards-hero-1440.avif"
      }
    ],
    "webp": "/images/resources/security-equipment-standards-hero.webp",
    "description": "UNEOM resource guide — security equipment standards",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "security uniforms",
      "tactical wear",
      "guard attire",
      "HCIS standards"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2026:04:06 08:56:41",
    "creatorTool": "UNEOM Editorial Pipeline",
    "alt": "Resource guide: security equipment standards — UNEOM expertise."
  },
  "resources/size-guide-hero": {
    "slug": "size-guide-hero",
    "category": "resources",
    "subCategory": null,
    "industry": null,
    "city": "riyadh",
    "path": "/images/resources/size-guide-hero.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/resources/size-guide-hero-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/resources/size-guide-hero-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/resources/size-guide-hero-1440.avif"
      }
    ],
    "webp": "/images/resources/size-guide-hero.webp",
    "description": "UNEOM resource guide — size guide",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2026:03:13 12:02:45",
    "creatorTool": "UNEOM Production House",
    "alt": "Resource guide: size guide — UNEOM expertise."
  },
  "resources/sustainability-guide-hero": {
    "slug": "sustainability-guide-hero",
    "category": "resources",
    "subCategory": null,
    "industry": null,
    "city": "riyadh",
    "path": "/images/resources/sustainability-guide-hero.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/resources/sustainability-guide-hero-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/resources/sustainability-guide-hero-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/resources/sustainability-guide-hero-1440.avif"
      }
    ],
    "webp": "/images/resources/sustainability-guide-hero.webp",
    "description": "UNEOM resource guide — sustainability guide",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:02:29 13:54:54",
    "creatorTool": "UNEOM Production House",
    "alt": "Resource guide: sustainability guide — UNEOM expertise."
  },
  "resources/weather-protection-hero": {
    "slug": "weather-protection-hero",
    "category": "resources",
    "subCategory": null,
    "industry": null,
    "city": "riyadh",
    "path": "/images/resources/weather-protection-hero.avif",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 640,
        "height": 360,
        "path": "/images/resources/weather-protection-hero-640.avif"
      },
      {
        "width": 960,
        "height": 540,
        "path": "/images/resources/weather-protection-hero-960.avif"
      },
      {
        "width": 1440,
        "height": 810,
        "path": "/images/resources/weather-protection-hero-1440.avif"
      }
    ],
    "webp": "/images/resources/weather-protection-hero.webp",
    "description": "UNEOM resource guide — weather protection",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:03:31 09:13:21",
    "creatorTool": "UNEOM Brand Studio",
    "alt": "Resource guide: weather protection — UNEOM expertise."
  }
};
