/**
 * Image Registry — trust category
 * Auto-generated by scripts/split-images-registry.mjs
 * 4 entries
 */

import type { ImageMetadata } from './types';

export const IMAGES_TRUST: Record<string, ImageMetadata> = {
  "trust/crn-verified": {
    "slug": "crn-verified",
    "category": "trust",
    "subCategory": null,
    "industry": null,
    "city": "riyadh",
    "path": "/images/trust/crn-verified.avif",
    "width": 800,
    "height": 400,
    "variants": [
      {
        "width": 400,
        "height": 200,
        "path": "/images/trust/crn-verified-400.avif"
      }
    ],
    "webp": "/images/trust/crn-verified.webp",
    "description": "UNEOM compliance verification badge — crn verified",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "compliance",
      "certification",
      "verified"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:11:14 16:22:44",
    "creatorTool": "UNEOM Production House",
    "alt": "CRN VERIFIED compliance verification badge — UNEOM certified."
  },
  "trust/iso-9001-verified": {
    "slug": "iso-9001-verified",
    "category": "trust",
    "subCategory": null,
    "industry": null,
    "city": "riyadh",
    "path": "/images/trust/iso-9001-verified.avif",
    "width": 800,
    "height": 400,
    "variants": [
      {
        "width": 400,
        "height": 200,
        "path": "/images/trust/iso-9001-verified-400.avif"
      }
    ],
    "webp": "/images/trust/iso-9001-verified.webp",
    "description": "UNEOM compliance verification badge — iso 9001 verified",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "compliance",
      "certification",
      "verified"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:10:10 12:40:48",
    "creatorTool": "UNEOM Production House",
    "alt": "ISO 9001 VERIFIED compliance verification badge — UNEOM certified."
  },
  "trust/maroof-verified": {
    "slug": "maroof-verified",
    "category": "trust",
    "subCategory": null,
    "industry": null,
    "city": "riyadh",
    "path": "/images/trust/maroof-verified.avif",
    "width": 800,
    "height": 400,
    "variants": [
      {
        "width": 400,
        "height": 200,
        "path": "/images/trust/maroof-verified-400.avif"
      }
    ],
    "webp": "/images/trust/maroof-verified.webp",
    "description": "UNEOM compliance verification badge — maroof verified",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "compliance",
      "certification",
      "verified"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2025:01:20 15:35:24",
    "creatorTool": "UNEOM Creative Department",
    "alt": "MAROOF VERIFIED compliance verification badge — UNEOM certified."
  },
  "trust/zatca-verified": {
    "slug": "zatca-verified",
    "category": "trust",
    "subCategory": null,
    "industry": null,
    "city": "riyadh",
    "path": "/images/trust/zatca-verified.avif",
    "width": 800,
    "height": 400,
    "variants": [
      {
        "width": 400,
        "height": 200,
        "path": "/images/trust/zatca-verified-400.avif"
      }
    ],
    "webp": "/images/trust/zatca-verified.webp",
    "description": "UNEOM compliance verification badge — zatca verified",
    "keywords": [
      "UNEOM",
      "Saudi Arabia",
      "professional uniforms",
      "B2B",
      "compliance",
      "certification",
      "verified"
    ],
    "gps": {
      "lat": 24.7136,
      "lng": 46.6753
    },
    "location": {
      "sublocation": "",
      "city": "",
      "state": "Saudi Arabia",
      "country": "Saudi Arabia",
      "countryCode": "SA"
    },
    "dateOriginal": "2024:11:28 18:52:51",
    "creatorTool": "UNEOM Design Lab",
    "alt": "ZATCA VERIFIED compliance verification badge — UNEOM certified."
  }
};
