/**
 * Image Registry — Types & Helpers
 * Auto-generated by scripts/split-images-registry.mjs
 */

export type ImageCategory =
  | 'heroes'
  | 'cities'
  | 'products'
  | 'fabrics'
  | 'case-studies'
  | 'blog'
  | 'resources'
  | 'trust'
  | 'process'
  | 'testimonials';

export interface ImageVariant {
  width: number;
  height: number;
  path: string;
}

export interface ImageMetadata {
  slug: string;
  category: ImageCategory;
  subCategory: string | null;
  industry: string | null;
  city: string | null;
  path: string;
  webp: string;
  variants: ImageVariant[];
  alt: string;
  description: string;
  width: number;
  height: number;
  gps: { lat: number; lng: number };
  location: {
    sublocation: string;
    city: string;
    state: string;
    country: string;
    countryCode: string;
  };
  dateOriginal: string;
  creatorTool: string;
  keywords: string[];
}

/**
 * Helper: build srcSet string for <picture> or <img>.
 */
export function buildSrcSet(img: ImageMetadata): string {
  return img.variants
    .map(v => `${v.path} ${v.width}w`)
    .concat(`${img.path} ${img.width}w`)
    .join(', ');
}

/**
 * Helper: build a sizes attribute for responsive images.
 */
export function defaultSizes(category: ImageCategory): string {
  switch (category) {
    case 'heroes':
    case 'cities':
    case 'blog':
    case 'resources':
    case 'process':
      return '(max-width: 768px) 100vw, (max-width: 1280px) 75vw, 1920px';
    case 'products':
    case 'fabrics':
      return '(max-width: 768px) 100vw, (max-width: 1280px) 50vw, 1200px';
    case 'case-studies':
      return '(max-width: 768px) 100vw, 50vw';
    case 'trust':
      return '(max-width: 768px) 50vw, 400px';
    case 'testimonials':
      return '(max-width: 768px) 50vw, 200px';
    default:
      return '100vw';
  }
}
